#!/usr/bin/env bash
#World wide web
line=$(dig "$2" "$1" | grep -A1 'anwser section:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
echo"$2 $line" | awk '{print "the subdomain " $1 " is a " $2 " record and points to " $3)'

if [ "$#" == 1 ]
then
info_of_domain "$1" "lb-01"
info_of_domain "$1" "www"
info_of_domain "$1" "web-01"
info_of_domain "$1" "web-02"

elif [ "$#" == 2 ]
then 
info_of_domain "$1" "$2"
fi
