#!/usr/bin/env bash
#Redirection
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
replacement_st="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "60i\\$replacement_st" /etc/nginx/sites-enabled/default
sudo service nginx restart
