#!/usr/bin/env bash
#Ceci n'est pas une page
sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/
replacement_st="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "60i\\$replacement_st" /etc/nginx/sites-enabled/default
sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error404.html
er404="\terror_page 404 /error404.html;"
sudo sed -i "59i\\$er404" /etc/nginx/sites-enabled/default
sudo service nginx restart
