#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo touch /etc/nginx/sites-available/hello_world.conf
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chown -R $USER:$USER /var/www/
replacement_st="server_name _;\n\trewrite ^\/replacement_st https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "60i\\$replacement_st" /etc/nginx/sites-enabled/default
sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error404.html
err404="\terror_page 404 /error404.html;"
sudo sed -i "59i\\$err404" /etc/nginx/sites-enabled/default
head="location \/ \{\n\t\tadd_head X-Served-By $HOSTNAME;"
sudo sed -i "s/location \/ {/$head/" /etc/nginx/sites-enabled/default
sudo service nginx restart
