#!/usr/bin/env bash
#Install your load balancer

sudo apt update
sudo apt-get -y install haproxy=1.6.\*
frontend="frontend front
    default_backend backservers
    bind *:80
    mode http"

backend="backend backservers
    balance roundrobin
    server 270819-web-01 54.234.81.198:80 check
    server 270819-web-02 52.87.219.252:80 check"

config="
$frontend
$backend"
sudo echo -e "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
