#!/usr/bin/env bash
#Setup a Primary-Replica infrastructure using MySQL
#This program is also distributed with certain software (including
# but not limited to OpenSSL) that is licensed under separate terms,
# as designated in a particular file or component or in included license
# documentation.  The authors of MySQL hereby grant you an additional
# permission to link the program and your derivative works with the
# separately licensed software that they have included with MySQL.
#
# This will be passed to all mysql clients
# It has been reported that passwords should be enclosed with ticks/quotes
# escpecially if they contain "#" chars...
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.

[mysqld]

pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log
symbolic-links  = 0
server-id       = 2
log_bin         = /var/log/mysql/mysql-bin.log
relay_log       = /var/log/mysql/mysql-relay-bin
binlog_do_db    = tyrell_corp
#log_slow_queries  = /var/log/mysql/mysql-slow.log
#long_query_time = 2
#log-queries-not-using-indexes
symbolic-links=0
