#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive out of it
date=$(date +%d-%m-%Y)
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf ${date}.tar.gz backup.sql
