#!/usr/bin/env bash
#Nginx likes port 80

sudo apt-get update
sudo apt-get -y install curl
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
